### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by Gexterious** [ApeSwapFinance/apeswap-frontend#1044]
Overview
Translate all language text to their correct individual language text and ensure it renders right on the pages.

Problem Statement
After switching to a different language some text still remain in English(Treasury Page and Cancel button on modals).
Also, some fonts tend to show in disrupted manner.

Requirements
As a user, i want to be able to switch to a language of my choice and all text should be translated to that same language.
As a user, i want to be able to switch to a language and see the text rendered properly on the page

<img width="950" alt="Screen Shot 2022-06-03 at 7 50 54 AM" src="https://user-images.githubusercontent.com/106542369/171874431-f486f003-f490-448b-b62e-c874975eb314.png">
<img width="1437" alt="Screen Shot 2022-06-03 at 3 35 02 PM" src="https://user-images.githubusercontent.com/106542369/171875613-93103402-0731-4409-98fa-c22039b49864.png">
<img width="427" alt="Screen Shot 2022-06-03 at 3 30 48 PM" src="https://user-images.githubusercontent.com/106542369/171874869-4cc577bf-1357-465f-8d50-f5656df3724c.png">

**Comment by pudgefury** [comment]
Hello, Is this need to implement?
