### ISSUE TITLE
Grant #007 - Wallet Address Overlay on mobile

### ISSUE THREAD

**Issue by robpark04** [ApeSwapFinance/apeswap-frontend#1053]
# Overview
![image](https://user-images.githubusercontent.com/94480152/173100413-1fdc6039-0849-42d5-9bc0-6c5f9e5adc36.png)

Wallet address overlay when clicked the address info, it should be displayed like '0x99992131....2933'.

**Comment by obiedobo** [comment]
Thanks ser, will get a sexy developer to work on this.

**Comment by robpark04** [comment]
Wanna join your team as a dev or QA engineer.
Please visit my portfolio website.
u can learn about me.

**Comment by obiedobo** [comment]
dev fix
