### ISSUE TITLE
Grant #010- Text Margin Ugly

### ISSUE THREAD

**Issue by robpark04** [ApeSwapFinance/apeswap-frontend#1064]
![image](https://user-images.githubusercontent.com/94480152/174156437-ca9b0b89-c60c-425c-8693-8e6ea64758bc.png)

Not beautiful text Marin

**Comment by obiedobo** [comment]
Thanks daddy will have a dev fix

**Comment by SandeepGumaste** [comment]
@obiedobo Is this issue fixed? I can contribute if it hasn't already been fixed

**Comment by obiedobo** [comment]
Hey @SandeepGumaste this issue is no longer relevant due to the SS-IAOs being taken down. Closing this out.
