### ISSUE TITLE
yarn installation

### ISSUE THREAD

**Issue by ToppinTroops** [ApeSwapFinance/apeswap-frontend#1146]
hi, i tried to clone the frontend and install yarn. But it says [Failed to replace env in config: ${NPM_TOKEN}] later i deleted the .npmrc file and tried to install yarn. Then it says [An unexpected error occurred: "https://registry.yarnpkg.com/@apeswapfinance%2fsdk: Not found".] Can someone help me solve this issue ?

**Comment by Prof-SD** [comment]
You need a personal access token to run the install. You can replace the variable in the .npmrc file or create a global variable called NPM_TOKEN.

Here is how to get an access token:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by gisho** [comment]
https://docs.npmjs.com/creating-and-viewing-access-tokens
