### ISSUE TITLE
SPACE ID SKD Integration

### ISSUE THREAD

**Issue by SoloSpaceID** [ApeSwapFinance/apeswap-frontend#1248]
Following this Integration documentation:
https://docs.space.id/integration/use-sid-to-enable-your-dapp

SPACE ID would like to have its .bnb names resolved and reverse-resolved in Apeswap.
The documentation link will send you to code examples that can be used, and should make the integration very easy.

**Benefits:**
1. Apeswap will get exposure to .bnb users
2. SPACE Id will promote the integration to its community
3. Apeswap users with .bnb domains will have enhanced social interactions, leading to a better community
4. Future financial incentives
5. Our SDK automatically resolves ENS and in the future, other name services so you don't have to spend any more time in the future doing additional name service integrations

**Resolving SID Names**
The first step to supporting SID in your application is making your application understand SID names, and accepting them anywhere an address is accepted. To understand how to do this, see [Resolving Names](https://github.com/contract-api/use-sidjs-sdk-to-resolve-names). If possible, when a user enters a SID name instead of an address, remember the SID name, not the address it currently resolves to. This makes it possible for users to update their SID names and have applications they used the name in automatically resolve to the new address, in the same way that you would expect your browser to automatically direct you to the new IP address if a site you use changes servers. If your application deals with user funds or other critical resources, you may want to keep track of the address a name resolves to and warn them when it changes, to ensure they are aware of the change. By accepting SID names in your application, you remove the need for users to copy and paste - or worse, type out - long and opaque wallet addresses, which leads to errors and lost funds.

**Support Reverse Resolution**
The second level of SID integration involves displaying SID names wherever your app currently displays addresses. If a user entered a SID in your DApp, you should retain this name and show it to them whenever you would normally show the address. If a user entered an address, or the address was obtained from elsewhere, you may still be able to show a SID name, by doing [Reverse Resolution](https://github.com/contract-api/use-sidjs-sdk-to-reverse-resolve-names). This permits you to find the canonical name for an address and display that when possible. If no canonical name is provided, your application can fall back to displaying the address as it did previously. By supporting reverse resolution, you make it easier for your users to identify accounts they interact with, associating them with a short human-readable name instead of a long opaque wallet address.

Example of where the Reverse Resolution would apply:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/111813533/188962000-828a240b-f903-4375-b2a0-022e77adfd6c.png">

<img width="862" alt="image" src="https://user-images.githubusercontent.com/111813533/188962070-4f7a5875-7274-4f55-bd29-bf84cda1b36a.png">

**Comment by obiedobo** [comment]
Thank you for submitting this issue! We would love to include this functionality in our UI, but at this exact moment we're quite backlogged.

Would you be open to submitting a PR to this repo (and potentially our UI kit as well, depending on implementation)?

If not, no worries, we will get this into our pipeline to the best of our ability.

**Comment by SoloSpaceID** [comment]
Hey Obie, please add it to your pipeline instead ❤
Have you connected with MonkeyBiz in regards to this? (unless that's you
haha)
We have reached 235k domains registered in less than a week after launch so
that's a lot of people that will love looking at Dapps that support it.
Our target was to hit 100k in 1 month 🔥

Cheers,
Solo
