### ISSUE TITLE
How can i customize Apeswap UI

### ISSUE THREAD

**Issue by clinks2** [ApeSwapFinance/apeswap-frontend#858]
I want to customize entire ui of apeswap but seems it using apeswap ui kit package, how can i do it by myself, clone apeswap-ui kit to new package? any docx i can refer to ?

**Comment by obiedobo** [comment]
In terms of a detailed guide, unfortunately there is no documentation on how to fork and adjust ApeSwap's UI.

But you can explore the UI kit and do it yourself here: https://github.com/ApeSwapFinance/apeswap-uikit
